name: master

on:
  push:
    tags:
      - 'v*'

env:
  PROJECT_ID: "315744"

jobs:
  changelog:
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.changelog.outputs.changelog }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get tag
        id: version
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Generate Changelog
        id: changelog
        uses: metcalfc/changelog-generator@v3.0.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Make Changelog Files
        run: |
          touch CHANGELOG.md
          mv CHANGELOG.md CHANGELOG_OLD.md
          echo "## (${{ steps.version.outputs.tag }})" > CHANGELOG.md
          echo "${{ steps.changelog.outputs.changelog }}" >> CHANGELOG.md
          cat CHANGELOG_OLD.md >> CHANGELOG.md
          echo "${{ steps.changelog.outputs.changelog }}" > CHANGELOG_SHORT.md
      - name: Save Changelog to Repo
        run: |
          git fetch
          git checkout master
          git config --global user.name 'CI Workflow'
          git config --global user.email 'noreply@nourl.com'
          
          pattern="## (${{ steps.version.outputs.tag }})"
          if [[ ! -n $(cat CHANGELOG_SHORT.md | grep $pattern) ]]; then git add CHANGELOG.md CHANGELOG_SHORT.md && git commit -am "Update CHANGELOG" && git push; fi
