name: master

on: workflow_dispatch

env:
  PROJECT_ID: "315744"

jobs:
  changelog:
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.changelog.outputs.changelog }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v3.0.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Save Changelog
        run: |
          echo "${{ steps.changelog.outputs.changelog }}" > CHANGELOG.md
          cat CHANGELOG.md
          git config --global user.name 'CI Workflow'
          git config --global user.email 'jjooss@live.nl'
          git commit -am "Update CHANGELOG.md"
          git push
      - name: Store changelog
        uses: actions/upload-artifact@v2
        with:
          name: changelog
          path: CHANGELOG.md
