name: master

on: workflow_dispatch

env:
  PROJECT_ID: "315744"

jobs:
  build-serverpack:
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.changelog.outputs.changelog }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare Modpack Files
        run: |
          mkdir -p serverpack/modpack
          cp -R modpack serverpack/modpack
      - name: Download mods
        run: |
          java -jar serverpack/ModpackDownloader-cli-0.7.1.jar -manifest modpack/manifest.json -folder modpack/overrides/mods
      - name: Make Server-pack
        run: |
          java -jar serverpack/ServerPackCreator-3.0.0-alpha.13 -cli
      - name: Rename Server-pack
        run: |
          mv serverpack/server-packs/_server_pack.zip serverpack/server-packs/${{ needs.modpack-info.outputs.projectname }}-${{ needs.modpack-info.outputs.tag }}-Server-Pack.zip
      - name: Store Pack in artifactory
        uses: actions/upload-artifact@v2
        with:
          name: serverpack
          path: serverpack/server-packs/${{ needs.modpack-info.outputs.projectname }}-${{ needs.modpack-info.outputs.tag }}-Server-Pack.zip
